### ISSUE TITLE
Demo Login details

### ISSUE THREAD

**Issue by wesleypearson** [Wave-Studio/Events#2]
Hey we are looking for a starting point for ticking for our upcoming event series. Would love to look at the capabilities of your system.

**Comment by quick007** [comment]
Hi @wesleypearson, Events is still in development and isn't ready for production. We're planning on doing our first beta test with an event in 2 weeks, but the earliest I we'd be able to offer any services publicly likely would be in mid December. 

Aside from that, is there any chance you can give us a little bit more insight on your use case? Our goal is to build a dead simple platform for event ticketing (that's free under 75 tickets). There's some complexity to it such as multiple event times, custom questions for tickets, etc. but we want to make sure that the features we decide to build matter to our users rather than adding features for the sake of adding features.

**Comment by quick007** [comment]
I'm closing this for now, feel free to respond and I'll be happy to reopen!
